#include <iostream>
#include <stdio.h>
#include <vector>
#include <dirent.h>
#include <cstring>
#include <sys/ioctl.h>
#include <unistd.h>
#include <string>
#include <termios.h>
#include <linux/sockios.h>
#include <linux/input.h>
#include <linux/inotify.h>
#include <cstdlib>
#include <time.h>
#include <fstream>
#define FIONREAD	0x541B
#include <main.h>
#include <displayfiles.h>
#include <filenamehighlight.h>
#include <keypressdetection.h>
#include <drawfilesbox.h>
#include <drawdrivesbox.h>
int menubar() {
if (menubarmode == false) {
setBackgroundColor(2);
printacharacterinanyterminallocation(1,1,"F");
printacharacterinanyterminallocation(1,2,"i");
printacharacterinanyterminallocation(1,3,"l");
printacharacterinanyterminallocation(1,4,"e");
}
else if (menubarmode == true) {
setBackgroundColor(3);
printacharacterinanyterminallocation(1,1,"F");
printacharacterinanyterminallocation(1,2,"i");
printacharacterinanyterminallocation(1,3,"l");
printacharacterinanyterminallocation(1,4,"e");
setBackgroundColor(2);
}
//if (x >= min && x <= max) {

    // x is within the range
//}
//setBackgroundColor(2);
for (int progresscolumn = 5;progresscolumn != columns;progresscolumn++) {
printacharacterinanyterminallocation(1,progresscolumn," ");
}
movecursortoanyterminallocation(1,1);
resetColors();
setBackgroundColor(2);
printacharacterinanyterminallocation(1,columns - 26,"P");
printacharacterinanyterminallocation(1,columns - 25,"r");
printacharacterinanyterminallocation(1,columns - 24,"e");
printacharacterinanyterminallocation(1,columns - 23,"s");
printacharacterinanyterminallocation(1,columns - 22,"s");
printacharacterinanyterminallocation(1,columns - 21," ");
printacharacterinanyterminallocation(1,columns - 20,"F");
printacharacterinanyterminallocation(1,columns - 19,"1");
printacharacterinanyterminallocation(1,columns - 18,"0");
printacharacterinanyterminallocation(1,columns - 17," ");
printacharacterinanyterminallocation(1,columns - 16,"o");
printacharacterinanyterminallocation(1,columns - 15,"r");
printacharacterinanyterminallocation(1,columns - 14,"");
printacharacterinanyterminallocation(1,columns - 13,"F");
printacharacterinanyterminallocation(1,columns - 12,"9");
printacharacterinanyterminallocation(1,columns - 11," ");
printacharacterinanyterminallocation(1,columns - 10,"f");
printacharacterinanyterminallocation(1,columns - 9,"o");
printacharacterinanyterminallocation(1,columns - 8,"r");
printacharacterinanyterminallocation(1,columns - 7," ");
printacharacterinanyterminallocation(1,columns - 6,"m");
printacharacterinanyterminallocation(1,columns - 5,"e");
printacharacterinanyterminallocation(1,columns - 4,"n");
printacharacterinanyterminallocation(1,columns - 3,"u");
printacharacterinanyterminallocation(1,columns - 2,"b");
printacharacterinanyterminallocation(1,columns - 1,"a");
printacharacterinanyterminallocation(1,columns,"r");
putchar('\n');
if (xcoordinateformenubar == 1 && menubarmode == true) {
setBackgroundColor(3);
printacharacterinanyterminallocation(3,2,"C");
printacharacterinanyterminallocation(3,3,"u");
printacharacterinanyterminallocation(3,4,"t");
printacharacterinanyterminallocation(3,5," ");
printacharacterinanyterminallocation(3,6," ");
printacharacterinanyterminallocation(3,7," ");
printacharacterinanyterminallocation(3,8," ");
printacharacterinanyterminallocation(3,9," ");
printacharacterinanyterminallocation(3,10," ");
printacharacterinanyterminallocation(3,11," ");
printacharacterinanyterminallocation(3,12," ");
printacharacterinanyterminallocation(3,13," ");
printacharacterinanyterminallocation(3,14," ");
printacharacterinanyterminallocation(3,15," ");
printacharacterinanyterminallocation(3,16," ");
printacharacterinanyterminallocation(3,17," ");
printacharacterinanyterminallocation(3,18," ");
printacharacterinanyterminallocation(3,19," ");
printacharacterinanyterminallocation(3,20," ");
printacharacterinanyterminallocation(3,21," ");
printacharacterinanyterminallocation(3,22," ");
printacharacterinanyterminallocation(3,23," ");
printacharacterinanyterminallocation(3,24," ");
setBackgroundColor(2);
printacharacterinanyterminallocation(4,2,"C");
printacharacterinanyterminallocation(4,3,"o");
printacharacterinanyterminallocation(4,4,"p");
printacharacterinanyterminallocation(4,5,"y");
printacharacterinanyterminallocation(4,6," ");
printacharacterinanyterminallocation(4,7," ");
printacharacterinanyterminallocation(4,8," ");
printacharacterinanyterminallocation(4,9," ");
printacharacterinanyterminallocation(4,10," ");
printacharacterinanyterminallocation(4,11," ");
printacharacterinanyterminallocation(4,12," ");
printacharacterinanyterminallocation(4,13," ");
printacharacterinanyterminallocation(4,14," ");
printacharacterinanyterminallocation(4,15," ");
printacharacterinanyterminallocation(4,16," ");
printacharacterinanyterminallocation(4,17," ");
printacharacterinanyterminallocation(4,18," ");
printacharacterinanyterminallocation(4,19," ");
printacharacterinanyterminallocation(4,20," ");
printacharacterinanyterminallocation(4,21," ");
printacharacterinanyterminallocation(4,22," ");
printacharacterinanyterminallocation(4,23," ");
printacharacterinanyterminallocation(4,24," ");
printacharacterinanyterminallocation(5,2,"P");
printacharacterinanyterminallocation(5,3,"a");
printacharacterinanyterminallocation(5,4,"s");
printacharacterinanyterminallocation(5,5,"t");
printacharacterinanyterminallocation(5,6,"e");
printacharacterinanyterminallocation(5,7," ");
printacharacterinanyterminallocation(5,8," ");
printacharacterinanyterminallocation(5,9," ");
printacharacterinanyterminallocation(5,10," ");
printacharacterinanyterminallocation(5,11," ");
printacharacterinanyterminallocation(5,12," ");
printacharacterinanyterminallocation(5,13," ");
printacharacterinanyterminallocation(5,14," ");
printacharacterinanyterminallocation(5,15," ");
printacharacterinanyterminallocation(5,16," ");
printacharacterinanyterminallocation(5,17," ");
printacharacterinanyterminallocation(5,18," ");
printacharacterinanyterminallocation(5,19," ");
printacharacterinanyterminallocation(5,20," ");
printacharacterinanyterminallocation(5,21," ");
printacharacterinanyterminallocation(5,22," ");
printacharacterinanyterminallocation(5,23," ");
printacharacterinanyterminallocation(5,24," ");
printacharacterinanyterminallocation(6,2,"R");
printacharacterinanyterminallocation(6,3,"e");
printacharacterinanyterminallocation(6,4,"n");
printacharacterinanyterminallocation(6,5,"a");
printacharacterinanyterminallocation(6,6,"m");
printacharacterinanyterminallocation(6,7,"e");
printacharacterinanyterminallocation(6,8," ");
printacharacterinanyterminallocation(6,9," ");
printacharacterinanyterminallocation(6,10," ");
printacharacterinanyterminallocation(6,11," ");
printacharacterinanyterminallocation(6,12," ");
printacharacterinanyterminallocation(6,13," ");
printacharacterinanyterminallocation(6,14," ");
printacharacterinanyterminallocation(6,15," ");
printacharacterinanyterminallocation(6,16," ");
printacharacterinanyterminallocation(6,17," ");
printacharacterinanyterminallocation(6,18," ");
printacharacterinanyterminallocation(6,19," ");
printacharacterinanyterminallocation(6,20," ");
printacharacterinanyterminallocation(6,21," ");
printacharacterinanyterminallocation(6,22," ");
printacharacterinanyterminallocation(6,23," ");
printacharacterinanyterminallocation(6,24," ");
printacharacterinanyterminallocation(7,2,"D");
printacharacterinanyterminallocation(7,3,"e");
printacharacterinanyterminallocation(7,4,"l");
printacharacterinanyterminallocation(7,5,"e");
printacharacterinanyterminallocation(7,6,"t");
printacharacterinanyterminallocation(7,7,"e");
printacharacterinanyterminallocation(7,8," ");
printacharacterinanyterminallocation(7,9," ");
printacharacterinanyterminallocation(7,10," ");
printacharacterinanyterminallocation(7,11," ");
printacharacterinanyterminallocation(7,12," ");
printacharacterinanyterminallocation(7,13," ");
printacharacterinanyterminallocation(7,14," ");
printacharacterinanyterminallocation(7,15," ");
printacharacterinanyterminallocation(7,16," ");
printacharacterinanyterminallocation(7,17," ");
printacharacterinanyterminallocation(7,18," ");
printacharacterinanyterminallocation(7,19," ");
printacharacterinanyterminallocation(7,20," ");
printacharacterinanyterminallocation(7,21," ");
printacharacterinanyterminallocation(7,22," ");
printacharacterinanyterminallocation(7,23," ");
printacharacterinanyterminallocation(7,24," ");
printacharacterinanyterminallocation(8,2,"N");
printacharacterinanyterminallocation(8,3,"e");
printacharacterinanyterminallocation(8,4,"w");
printacharacterinanyterminallocation(8,5," ");
printacharacterinanyterminallocation(8,6,"f");
printacharacterinanyterminallocation(8,7,"o");
printacharacterinanyterminallocation(8,8,"l");
printacharacterinanyterminallocation(8,9,"d");
printacharacterinanyterminallocation(8,10,"e");
printacharacterinanyterminallocation(8,11,"r");
printacharacterinanyterminallocation(8,12," ");
printacharacterinanyterminallocation(8,13," ");
printacharacterinanyterminallocation(8,14," ");
printacharacterinanyterminallocation(8,15," ");
printacharacterinanyterminallocation(8,16," ");
printacharacterinanyterminallocation(8,17," ");
printacharacterinanyterminallocation(8,18," ");
printacharacterinanyterminallocation(8,19," ");
printacharacterinanyterminallocation(8,20," ");
printacharacterinanyterminallocation(8,21," ");
printacharacterinanyterminallocation(8,22," ");
printacharacterinanyterminallocation(8,23," ");
printacharacterinanyterminallocation(8,24," ");
printacharacterinanyterminallocation(9,2,"E");
printacharacterinanyterminallocation(9,3,"x");
printacharacterinanyterminallocation(9,4,"i");
printacharacterinanyterminallocation(9,5,"t");
printacharacterinanyterminallocation(9,6," ");
printacharacterinanyterminallocation(9,7," ");
printacharacterinanyterminallocation(9,8," ");
printacharacterinanyterminallocation(9,9," ");
printacharacterinanyterminallocation(9,10," ");
printacharacterinanyterminallocation(9,11," ");
printacharacterinanyterminallocation(9,12," ");
printacharacterinanyterminallocation(9,13," ");
printacharacterinanyterminallocation(9,14," ");
printacharacterinanyterminallocation(9,15," ");
printacharacterinanyterminallocation(9,16," ");
printacharacterinanyterminallocation(9,17," ");
printacharacterinanyterminallocation(9,18," ");
printacharacterinanyterminallocation(9,19," ");
printacharacterinanyterminallocation(9,20," ");
printacharacterinanyterminallocation(9,21," ");
printacharacterinanyterminallocation(9,22," ");
printacharacterinanyterminallocation(9,23," ");
printacharacterinanyterminallocation(9,24," ");
putchar('\n');
}
else if (xcoordinateformenubar == 2 && menubarmode == true) {
printacharacterinanyterminallocation(3,2,"C");
printacharacterinanyterminallocation(3,3,"u");
printacharacterinanyterminallocation(3,4,"t");
printacharacterinanyterminallocation(3,5," ");
printacharacterinanyterminallocation(3,6," ");
printacharacterinanyterminallocation(3,7," ");
printacharacterinanyterminallocation(3,8," ");
printacharacterinanyterminallocation(3,9," ");
printacharacterinanyterminallocation(3,10," ");
printacharacterinanyterminallocation(3,11," ");
printacharacterinanyterminallocation(3,12," ");
printacharacterinanyterminallocation(3,13," ");
printacharacterinanyterminallocation(3,14," ");
printacharacterinanyterminallocation(3,15," ");
printacharacterinanyterminallocation(3,16," ");
printacharacterinanyterminallocation(3,17," ");
printacharacterinanyterminallocation(3,18," ");
printacharacterinanyterminallocation(3,19," ");
printacharacterinanyterminallocation(3,20," ");
printacharacterinanyterminallocation(3,21," ");
printacharacterinanyterminallocation(3,22," ");
printacharacterinanyterminallocation(3,23," ");
printacharacterinanyterminallocation(3,24," ");
setBackgroundColor(3);
printacharacterinanyterminallocation(4,2,"C");
printacharacterinanyterminallocation(4,3,"o");
printacharacterinanyterminallocation(4,4,"p");
printacharacterinanyterminallocation(4,5,"y");
printacharacterinanyterminallocation(4,6," ");
printacharacterinanyterminallocation(4,7," ");
printacharacterinanyterminallocation(4,8," ");
printacharacterinanyterminallocation(4,9," ");
printacharacterinanyterminallocation(4,10," ");
printacharacterinanyterminallocation(4,11," ");
printacharacterinanyterminallocation(4,12," ");
printacharacterinanyterminallocation(4,13," ");
printacharacterinanyterminallocation(4,14," ");
printacharacterinanyterminallocation(4,15," ");
printacharacterinanyterminallocation(4,16," ");
printacharacterinanyterminallocation(4,17," ");
printacharacterinanyterminallocation(4,18," ");
printacharacterinanyterminallocation(4,19," ");
printacharacterinanyterminallocation(4,20," ");
printacharacterinanyterminallocation(4,21," ");
printacharacterinanyterminallocation(4,22," ");
printacharacterinanyterminallocation(4,23," ");
printacharacterinanyterminallocation(4,24," ");
setBackgroundColor(2);
printacharacterinanyterminallocation(5,2,"P");
printacharacterinanyterminallocation(5,3,"a");
printacharacterinanyterminallocation(5,4,"s");
printacharacterinanyterminallocation(5,5,"t");
printacharacterinanyterminallocation(5,6,"e");
printacharacterinanyterminallocation(5,7," ");
printacharacterinanyterminallocation(5,8," ");
printacharacterinanyterminallocation(5,9," ");
printacharacterinanyterminallocation(5,10," ");
printacharacterinanyterminallocation(5,11," ");
printacharacterinanyterminallocation(5,12," ");
printacharacterinanyterminallocation(5,13," ");
printacharacterinanyterminallocation(5,14," ");
printacharacterinanyterminallocation(5,15," ");
printacharacterinanyterminallocation(5,16," ");
printacharacterinanyterminallocation(5,17," ");
printacharacterinanyterminallocation(5,18," ");
printacharacterinanyterminallocation(5,19," ");
printacharacterinanyterminallocation(5,20," ");
printacharacterinanyterminallocation(5,21," ");
printacharacterinanyterminallocation(5,22," ");
printacharacterinanyterminallocation(5,23," ");
printacharacterinanyterminallocation(5,24," ");
printacharacterinanyterminallocation(6,2,"R");
printacharacterinanyterminallocation(6,3,"e");
printacharacterinanyterminallocation(6,4,"n");
printacharacterinanyterminallocation(6,5,"a");
printacharacterinanyterminallocation(6,6,"m");
printacharacterinanyterminallocation(6,7,"e");
printacharacterinanyterminallocation(6,8," ");
printacharacterinanyterminallocation(6,9," ");
printacharacterinanyterminallocation(6,10," ");
printacharacterinanyterminallocation(6,11," ");
printacharacterinanyterminallocation(6,12," ");
printacharacterinanyterminallocation(6,13," ");
printacharacterinanyterminallocation(6,14," ");
printacharacterinanyterminallocation(6,15," ");
printacharacterinanyterminallocation(6,16," ");
printacharacterinanyterminallocation(6,17," ");
printacharacterinanyterminallocation(6,18," ");
printacharacterinanyterminallocation(6,19," ");
printacharacterinanyterminallocation(6,20," ");
printacharacterinanyterminallocation(6,21," ");
printacharacterinanyterminallocation(6,22," ");
printacharacterinanyterminallocation(6,23," ");
printacharacterinanyterminallocation(6,24," ");
printacharacterinanyterminallocation(7,2,"D");
printacharacterinanyterminallocation(7,3,"e");
printacharacterinanyterminallocation(7,4,"l");
printacharacterinanyterminallocation(7,5,"e");
printacharacterinanyterminallocation(7,6,"t");
printacharacterinanyterminallocation(7,7,"e");
printacharacterinanyterminallocation(7,8," ");
printacharacterinanyterminallocation(7,9," ");
printacharacterinanyterminallocation(7,10," ");
printacharacterinanyterminallocation(7,11," ");
printacharacterinanyterminallocation(7,12," ");
printacharacterinanyterminallocation(7,13," ");
printacharacterinanyterminallocation(7,14," ");
printacharacterinanyterminallocation(7,15," ");
printacharacterinanyterminallocation(7,16," ");
printacharacterinanyterminallocation(7,17," ");
printacharacterinanyterminallocation(7,18," ");
printacharacterinanyterminallocation(7,19," ");
printacharacterinanyterminallocation(7,20," ");
printacharacterinanyterminallocation(7,21," ");
printacharacterinanyterminallocation(7,22," ");
printacharacterinanyterminallocation(7,23," ");
printacharacterinanyterminallocation(7,24," ");
printacharacterinanyterminallocation(8,2,"N");
printacharacterinanyterminallocation(8,3,"e");
printacharacterinanyterminallocation(8,4,"w");
printacharacterinanyterminallocation(8,5," ");
printacharacterinanyterminallocation(8,6,"f");
printacharacterinanyterminallocation(8,7,"o");
printacharacterinanyterminallocation(8,8,"l");
printacharacterinanyterminallocation(8,9,"d");
printacharacterinanyterminallocation(8,10,"e");
printacharacterinanyterminallocation(8,11,"r");
printacharacterinanyterminallocation(8,12," ");
printacharacterinanyterminallocation(8,13," ");
printacharacterinanyterminallocation(8,14," ");
printacharacterinanyterminallocation(8,15," ");
printacharacterinanyterminallocation(8,16," ");
printacharacterinanyterminallocation(8,17," ");
printacharacterinanyterminallocation(8,18," ");
printacharacterinanyterminallocation(8,19," ");
printacharacterinanyterminallocation(8,20," ");
printacharacterinanyterminallocation(8,21," ");
printacharacterinanyterminallocation(8,22," ");
printacharacterinanyterminallocation(8,23," ");
printacharacterinanyterminallocation(8,24," ");
printacharacterinanyterminallocation(9,2,"E");
printacharacterinanyterminallocation(9,3,"x");
printacharacterinanyterminallocation(9,4,"i");
printacharacterinanyterminallocation(9,5,"t");
printacharacterinanyterminallocation(9,6," ");
printacharacterinanyterminallocation(9,7," ");
printacharacterinanyterminallocation(9,8," ");
printacharacterinanyterminallocation(9,9," ");
printacharacterinanyterminallocation(9,10," ");
printacharacterinanyterminallocation(9,11," ");
printacharacterinanyterminallocation(9,12," ");
printacharacterinanyterminallocation(9,13," ");
printacharacterinanyterminallocation(9,14," ");
printacharacterinanyterminallocation(9,15," ");
printacharacterinanyterminallocation(9,16," ");
printacharacterinanyterminallocation(9,17," ");
printacharacterinanyterminallocation(9,18," ");
printacharacterinanyterminallocation(9,19," ");
printacharacterinanyterminallocation(9,20," ");
printacharacterinanyterminallocation(9,21," ");
printacharacterinanyterminallocation(9,22," ");
printacharacterinanyterminallocation(9,23," ");
printacharacterinanyterminallocation(9,24," ");
putchar('\n');
}
else if (xcoordinateformenubar == 3 && menubarmode == true){
printacharacterinanyterminallocation(3,2,"C");
printacharacterinanyterminallocation(3,3,"u");
printacharacterinanyterminallocation(3,4,"t");
printacharacterinanyterminallocation(3,5," ");
printacharacterinanyterminallocation(3,6," ");
printacharacterinanyterminallocation(3,7," ");
printacharacterinanyterminallocation(3,8," ");
printacharacterinanyterminallocation(3,9," ");
printacharacterinanyterminallocation(3,10," ");
printacharacterinanyterminallocation(3,11," ");
printacharacterinanyterminallocation(3,12," ");
printacharacterinanyterminallocation(3,13," ");
printacharacterinanyterminallocation(3,14," ");
printacharacterinanyterminallocation(3,15," ");
printacharacterinanyterminallocation(3,16," ");
printacharacterinanyterminallocation(3,17," ");
printacharacterinanyterminallocation(3,18," ");
printacharacterinanyterminallocation(3,19," ");
printacharacterinanyterminallocation(3,20," ");
printacharacterinanyterminallocation(3,21," ");
printacharacterinanyterminallocation(3,22," ");
printacharacterinanyterminallocation(3,23," ");
printacharacterinanyterminallocation(3,24," ");
printacharacterinanyterminallocation(4,2,"C");
printacharacterinanyterminallocation(4,3,"o");
printacharacterinanyterminallocation(4,4,"p");
printacharacterinanyterminallocation(4,5,"y");
printacharacterinanyterminallocation(4,6," ");
printacharacterinanyterminallocation(4,7," ");
printacharacterinanyterminallocation(4,8," ");
printacharacterinanyterminallocation(4,9," ");
printacharacterinanyterminallocation(4,10," ");
printacharacterinanyterminallocation(4,11," ");
printacharacterinanyterminallocation(4,12," ");
printacharacterinanyterminallocation(4,13," ");
printacharacterinanyterminallocation(4,14," ");
printacharacterinanyterminallocation(4,15," ");
printacharacterinanyterminallocation(4,16," ");
printacharacterinanyterminallocation(4,17," ");
printacharacterinanyterminallocation(4,18," ");
printacharacterinanyterminallocation(4,19," ");
printacharacterinanyterminallocation(4,20," ");
printacharacterinanyterminallocation(4,21," ");
printacharacterinanyterminallocation(4,22," ");
printacharacterinanyterminallocation(4,23," ");
printacharacterinanyterminallocation(4,24," ");
setBackgroundColor(3);
printacharacterinanyterminallocation(5,2,"P");
printacharacterinanyterminallocation(5,3,"a");
printacharacterinanyterminallocation(5,4,"s");
printacharacterinanyterminallocation(5,5,"t");
printacharacterinanyterminallocation(5,6,"e");
printacharacterinanyterminallocation(5,7," ");
printacharacterinanyterminallocation(5,8," ");
printacharacterinanyterminallocation(5,9," ");
printacharacterinanyterminallocation(5,10," ");
printacharacterinanyterminallocation(5,11," ");
printacharacterinanyterminallocation(5,12," ");
printacharacterinanyterminallocation(5,13," ");
printacharacterinanyterminallocation(5,14," ");
printacharacterinanyterminallocation(5,15," ");
printacharacterinanyterminallocation(5,16," ");
printacharacterinanyterminallocation(5,17," ");
printacharacterinanyterminallocation(5,18," ");
printacharacterinanyterminallocation(5,19," ");
printacharacterinanyterminallocation(5,20," ");
printacharacterinanyterminallocation(5,21," ");
printacharacterinanyterminallocation(5,22," ");
printacharacterinanyterminallocation(5,23," ");
printacharacterinanyterminallocation(5,24," ");
setBackgroundColor(2);
printacharacterinanyterminallocation(6,2,"R");
printacharacterinanyterminallocation(6,3,"e");
printacharacterinanyterminallocation(6,4,"n");
printacharacterinanyterminallocation(6,5,"a");
printacharacterinanyterminallocation(6,6,"m");
printacharacterinanyterminallocation(6,7,"e");
printacharacterinanyterminallocation(6,8," ");
printacharacterinanyterminallocation(6,9," ");
printacharacterinanyterminallocation(6,10," ");
printacharacterinanyterminallocation(6,11," ");
printacharacterinanyterminallocation(6,12," ");
printacharacterinanyterminallocation(6,13," ");
printacharacterinanyterminallocation(6,14," ");
printacharacterinanyterminallocation(6,15," ");
printacharacterinanyterminallocation(6,16," ");
printacharacterinanyterminallocation(6,17," ");
printacharacterinanyterminallocation(6,18," ");
printacharacterinanyterminallocation(6,19," ");
printacharacterinanyterminallocation(6,20," ");
printacharacterinanyterminallocation(6,21," ");
printacharacterinanyterminallocation(6,22," ");
printacharacterinanyterminallocation(6,23," ");
printacharacterinanyterminallocation(6,24," ");
printacharacterinanyterminallocation(7,2,"D");
printacharacterinanyterminallocation(7,3,"e");
printacharacterinanyterminallocation(7,4,"l");
printacharacterinanyterminallocation(7,5,"e");
printacharacterinanyterminallocation(7,6,"t");
printacharacterinanyterminallocation(7,7,"e");
printacharacterinanyterminallocation(7,8," ");
printacharacterinanyterminallocation(7,9," ");
printacharacterinanyterminallocation(7,10," ");
printacharacterinanyterminallocation(7,11," ");
printacharacterinanyterminallocation(7,12," ");
printacharacterinanyterminallocation(7,13," ");
printacharacterinanyterminallocation(7,14," ");
printacharacterinanyterminallocation(7,15," ");
printacharacterinanyterminallocation(7,16," ");
printacharacterinanyterminallocation(7,17," ");
printacharacterinanyterminallocation(7,18," ");
printacharacterinanyterminallocation(7,19," ");
printacharacterinanyterminallocation(7,20," ");
printacharacterinanyterminallocation(7,21," ");
printacharacterinanyterminallocation(7,22," ");
printacharacterinanyterminallocation(7,23," ");
printacharacterinanyterminallocation(7,24," ");
printacharacterinanyterminallocation(8,2,"N");
printacharacterinanyterminallocation(8,3,"e");
printacharacterinanyterminallocation(8,4,"w");
printacharacterinanyterminallocation(8,5," ");
printacharacterinanyterminallocation(8,6,"f");
printacharacterinanyterminallocation(8,7,"o");
printacharacterinanyterminallocation(8,8,"l");
printacharacterinanyterminallocation(8,9,"d");
printacharacterinanyterminallocation(8,10,"e");
printacharacterinanyterminallocation(8,11,"r");
printacharacterinanyterminallocation(8,12," ");
printacharacterinanyterminallocation(8,13," ");
printacharacterinanyterminallocation(8,14," ");
printacharacterinanyterminallocation(8,15," ");
printacharacterinanyterminallocation(8,16," ");
printacharacterinanyterminallocation(8,17," ");
printacharacterinanyterminallocation(8,18," ");
printacharacterinanyterminallocation(8,19," ");
printacharacterinanyterminallocation(8,20," ");
printacharacterinanyterminallocation(8,21," ");
printacharacterinanyterminallocation(8,22," ");
printacharacterinanyterminallocation(8,23," ");
printacharacterinanyterminallocation(8,24," ");
printacharacterinanyterminallocation(9,2,"E");
printacharacterinanyterminallocation(9,3,"x");
printacharacterinanyterminallocation(9,4,"i");
printacharacterinanyterminallocation(9,5,"t");
printacharacterinanyterminallocation(9,6," ");
printacharacterinanyterminallocation(9,7," ");
printacharacterinanyterminallocation(9,8," ");
printacharacterinanyterminallocation(9,9," ");
printacharacterinanyterminallocation(9,10," ");
printacharacterinanyterminallocation(9,11," ");
printacharacterinanyterminallocation(9,12," ");
printacharacterinanyterminallocation(9,13," ");
printacharacterinanyterminallocation(9,14," ");
printacharacterinanyterminallocation(9,15," ");
printacharacterinanyterminallocation(9,16," ");
printacharacterinanyterminallocation(9,17," ");
printacharacterinanyterminallocation(9,18," ");
printacharacterinanyterminallocation(9,19," ");
printacharacterinanyterminallocation(9,20," ");
printacharacterinanyterminallocation(9,21," ");
printacharacterinanyterminallocation(9,22," ");
printacharacterinanyterminallocation(9,23," ");
printacharacterinanyterminallocation(9,24," ");
putchar('\n');
}
else if (xcoordinateformenubar == 4 && menubarmode == true){
printacharacterinanyterminallocation(3,2,"C");
printacharacterinanyterminallocation(3,3,"u");
printacharacterinanyterminallocation(3,4,"t");
printacharacterinanyterminallocation(3,5," ");
printacharacterinanyterminallocation(3,6," ");
printacharacterinanyterminallocation(3,7," ");
printacharacterinanyterminallocation(3,8," ");
printacharacterinanyterminallocation(3,9," ");
printacharacterinanyterminallocation(3,10," ");
printacharacterinanyterminallocation(3,11," ");
printacharacterinanyterminallocation(3,12," ");
printacharacterinanyterminallocation(3,13," ");
printacharacterinanyterminallocation(3,14," ");
printacharacterinanyterminallocation(3,15," ");
printacharacterinanyterminallocation(3,16," ");
printacharacterinanyterminallocation(3,17," ");
printacharacterinanyterminallocation(3,18," ");
printacharacterinanyterminallocation(3,19," ");
printacharacterinanyterminallocation(3,20," ");
printacharacterinanyterminallocation(3,21," ");
printacharacterinanyterminallocation(3,22," ");
printacharacterinanyterminallocation(3,23," ");
printacharacterinanyterminallocation(3,24," ");
printacharacterinanyterminallocation(4,2,"C");
printacharacterinanyterminallocation(4,3,"o");
printacharacterinanyterminallocation(4,4,"p");
printacharacterinanyterminallocation(4,5,"y");
printacharacterinanyterminallocation(4,6," ");
printacharacterinanyterminallocation(4,7," ");
printacharacterinanyterminallocation(4,8," ");
printacharacterinanyterminallocation(4,9," ");
printacharacterinanyterminallocation(4,10," ");
printacharacterinanyterminallocation(4,11," ");
printacharacterinanyterminallocation(4,12," ");
printacharacterinanyterminallocation(4,13," ");
printacharacterinanyterminallocation(4,14," ");
printacharacterinanyterminallocation(4,15," ");
printacharacterinanyterminallocation(4,16," ");
printacharacterinanyterminallocation(4,17," ");
printacharacterinanyterminallocation(4,18," ");
printacharacterinanyterminallocation(4,19," ");
printacharacterinanyterminallocation(4,20," ");
printacharacterinanyterminallocation(4,21," ");
printacharacterinanyterminallocation(4,22," ");
printacharacterinanyterminallocation(4,23," ");
printacharacterinanyterminallocation(4,24," ");
printacharacterinanyterminallocation(5,2,"P");
printacharacterinanyterminallocation(5,3,"a");
printacharacterinanyterminallocation(5,4,"s");
printacharacterinanyterminallocation(5,5,"t");
printacharacterinanyterminallocation(5,6,"e");
printacharacterinanyterminallocation(5,7," ");
printacharacterinanyterminallocation(5,8," ");
printacharacterinanyterminallocation(5,9," ");
printacharacterinanyterminallocation(5,10," ");
printacharacterinanyterminallocation(5,11," ");
printacharacterinanyterminallocation(5,12," ");
printacharacterinanyterminallocation(5,13," ");
printacharacterinanyterminallocation(5,14," ");
printacharacterinanyterminallocation(5,15," ");
printacharacterinanyterminallocation(5,16," ");
printacharacterinanyterminallocation(5,17," ");
printacharacterinanyterminallocation(5,18," ");
printacharacterinanyterminallocation(5,19," ");
printacharacterinanyterminallocation(5,20," ");
printacharacterinanyterminallocation(5,21," ");
printacharacterinanyterminallocation(5,22," ");
printacharacterinanyterminallocation(5,23," ");
printacharacterinanyterminallocation(5,24," ");
setBackgroundColor(3);
printacharacterinanyterminallocation(6,2,"R");
printacharacterinanyterminallocation(6,3,"e");
printacharacterinanyterminallocation(6,4,"n");
printacharacterinanyterminallocation(6,5,"a");
printacharacterinanyterminallocation(6,6,"m");
printacharacterinanyterminallocation(6,7,"e");
printacharacterinanyterminallocation(6,8," ");
printacharacterinanyterminallocation(6,9," ");
printacharacterinanyterminallocation(6,10," ");
printacharacterinanyterminallocation(6,11," ");
printacharacterinanyterminallocation(6,12," ");
printacharacterinanyterminallocation(6,13," ");
printacharacterinanyterminallocation(6,14," ");
printacharacterinanyterminallocation(6,15," ");
printacharacterinanyterminallocation(6,16," ");
printacharacterinanyterminallocation(6,17," ");
printacharacterinanyterminallocation(6,18," ");
printacharacterinanyterminallocation(6,19," ");
printacharacterinanyterminallocation(6,20," ");
printacharacterinanyterminallocation(6,21," ");
printacharacterinanyterminallocation(6,22," ");
printacharacterinanyterminallocation(6,23," ");
printacharacterinanyterminallocation(6,24," ");
setBackgroundColor(2);
printacharacterinanyterminallocation(7,2,"D");
printacharacterinanyterminallocation(7,3,"e");
printacharacterinanyterminallocation(7,4,"l");
printacharacterinanyterminallocation(7,5,"e");
printacharacterinanyterminallocation(7,6,"t");
printacharacterinanyterminallocation(7,7,"e");
printacharacterinanyterminallocation(7,8," ");
printacharacterinanyterminallocation(7,9," ");
printacharacterinanyterminallocation(7,10," ");
printacharacterinanyterminallocation(7,11," ");
printacharacterinanyterminallocation(7,12," ");
printacharacterinanyterminallocation(7,13," ");
printacharacterinanyterminallocation(7,14," ");
printacharacterinanyterminallocation(7,15," ");
printacharacterinanyterminallocation(7,16," ");
printacharacterinanyterminallocation(7,17," ");
printacharacterinanyterminallocation(7,18," ");
printacharacterinanyterminallocation(7,19," ");
printacharacterinanyterminallocation(7,20," ");
printacharacterinanyterminallocation(7,21," ");
printacharacterinanyterminallocation(7,22," ");
printacharacterinanyterminallocation(7,23," ");
printacharacterinanyterminallocation(7,24," ");
printacharacterinanyterminallocation(8,2,"N");
printacharacterinanyterminallocation(8,3,"e");
printacharacterinanyterminallocation(8,4,"w");
printacharacterinanyterminallocation(8,5," ");
printacharacterinanyterminallocation(8,6,"f");
printacharacterinanyterminallocation(8,7,"o");
printacharacterinanyterminallocation(8,8,"l");
printacharacterinanyterminallocation(8,9,"d");
printacharacterinanyterminallocation(8,10,"e");
printacharacterinanyterminallocation(8,11,"r");
printacharacterinanyterminallocation(8,12," ");
printacharacterinanyterminallocation(8,13," ");
printacharacterinanyterminallocation(8,14," ");
printacharacterinanyterminallocation(8,15," ");
printacharacterinanyterminallocation(8,16," ");
printacharacterinanyterminallocation(8,17," ");
printacharacterinanyterminallocation(8,18," ");
printacharacterinanyterminallocation(8,19," ");
printacharacterinanyterminallocation(8,20," ");
printacharacterinanyterminallocation(8,21," ");
printacharacterinanyterminallocation(8,22," ");
printacharacterinanyterminallocation(8,23," ");
printacharacterinanyterminallocation(8,24," ");
printacharacterinanyterminallocation(9,2,"E");
printacharacterinanyterminallocation(9,3,"x");
printacharacterinanyterminallocation(9,4,"i");
printacharacterinanyterminallocation(9,5,"t");
printacharacterinanyterminallocation(9,6," ");
printacharacterinanyterminallocation(9,7," ");
printacharacterinanyterminallocation(9,8," ");
printacharacterinanyterminallocation(9,9," ");
printacharacterinanyterminallocation(9,10," ");
printacharacterinanyterminallocation(9,11," ");
printacharacterinanyterminallocation(9,12," ");
printacharacterinanyterminallocation(9,13," ");
printacharacterinanyterminallocation(9,14," ");
printacharacterinanyterminallocation(9,15," ");
printacharacterinanyterminallocation(9,16," ");
printacharacterinanyterminallocation(9,17," ");
printacharacterinanyterminallocation(9,18," ");
printacharacterinanyterminallocation(9,19," ");
printacharacterinanyterminallocation(9,20," ");
printacharacterinanyterminallocation(9,21," ");
printacharacterinanyterminallocation(9,22," ");
printacharacterinanyterminallocation(9,23," ");
printacharacterinanyterminallocation(9,24," ");
putchar('\n');
}
else if (xcoordinateformenubar == 5 && menubarmode == true){
printacharacterinanyterminallocation(3,2,"C");
printacharacterinanyterminallocation(3,3,"u");
printacharacterinanyterminallocation(3,4,"t");
printacharacterinanyterminallocation(3,5," ");
printacharacterinanyterminallocation(3,6," ");
printacharacterinanyterminallocation(3,7," ");
printacharacterinanyterminallocation(3,8," ");
printacharacterinanyterminallocation(3,9," ");
printacharacterinanyterminallocation(3,10," ");
printacharacterinanyterminallocation(3,11," ");
printacharacterinanyterminallocation(3,12," ");
printacharacterinanyterminallocation(3,13," ");
printacharacterinanyterminallocation(3,14," ");
printacharacterinanyterminallocation(3,15," ");
printacharacterinanyterminallocation(3,16," ");
printacharacterinanyterminallocation(3,17," ");
printacharacterinanyterminallocation(3,18," ");
printacharacterinanyterminallocation(3,19," ");
printacharacterinanyterminallocation(3,20," ");
printacharacterinanyterminallocation(3,21," ");
printacharacterinanyterminallocation(3,22," ");
printacharacterinanyterminallocation(3,23," ");
printacharacterinanyterminallocation(3,24," ");
printacharacterinanyterminallocation(4,2,"C");
printacharacterinanyterminallocation(4,3,"o");
printacharacterinanyterminallocation(4,4,"p");
printacharacterinanyterminallocation(4,5,"y");
printacharacterinanyterminallocation(4,6," ");
printacharacterinanyterminallocation(4,7," ");
printacharacterinanyterminallocation(4,8," ");
printacharacterinanyterminallocation(4,9," ");
printacharacterinanyterminallocation(4,10," ");
printacharacterinanyterminallocation(4,11," ");
printacharacterinanyterminallocation(4,12," ");
printacharacterinanyterminallocation(4,13," ");
printacharacterinanyterminallocation(4,14," ");
printacharacterinanyterminallocation(4,15," ");
printacharacterinanyterminallocation(4,16," ");
printacharacterinanyterminallocation(4,17," ");
printacharacterinanyterminallocation(4,18," ");
printacharacterinanyterminallocation(4,19," ");
printacharacterinanyterminallocation(4,20," ");
printacharacterinanyterminallocation(4,21," ");
printacharacterinanyterminallocation(4,22," ");
printacharacterinanyterminallocation(4,23," ");
printacharacterinanyterminallocation(4,24," ");
printacharacterinanyterminallocation(5,2,"P");
printacharacterinanyterminallocation(5,3,"a");
printacharacterinanyterminallocation(5,4,"s");
printacharacterinanyterminallocation(5,5,"t");
printacharacterinanyterminallocation(5,6,"e");
printacharacterinanyterminallocation(5,7," ");
printacharacterinanyterminallocation(5,8," ");
printacharacterinanyterminallocation(5,9," ");
printacharacterinanyterminallocation(5,10," ");
printacharacterinanyterminallocation(5,11," ");
printacharacterinanyterminallocation(5,12," ");
printacharacterinanyterminallocation(5,13," ");
printacharacterinanyterminallocation(5,14," ");
printacharacterinanyterminallocation(5,15," ");
printacharacterinanyterminallocation(5,16," ");
printacharacterinanyterminallocation(5,17," ");
printacharacterinanyterminallocation(5,18," ");
printacharacterinanyterminallocation(5,19," ");
printacharacterinanyterminallocation(5,20," ");
printacharacterinanyterminallocation(5,21," ");
printacharacterinanyterminallocation(5,22," ");
printacharacterinanyterminallocation(5,23," ");
printacharacterinanyterminallocation(5,24," ");
printacharacterinanyterminallocation(6,2,"R");
printacharacterinanyterminallocation(6,3,"e");
printacharacterinanyterminallocation(6,4,"n");
printacharacterinanyterminallocation(6,5,"a");
printacharacterinanyterminallocation(6,6,"m");
printacharacterinanyterminallocation(6,7,"e");
printacharacterinanyterminallocation(6,8," ");
printacharacterinanyterminallocation(6,9," ");
printacharacterinanyterminallocation(6,10," ");
printacharacterinanyterminallocation(6,11," ");
printacharacterinanyterminallocation(6,12," ");
printacharacterinanyterminallocation(6,13," ");
printacharacterinanyterminallocation(6,14," ");
printacharacterinanyterminallocation(6,15," ");
printacharacterinanyterminallocation(6,16," ");
printacharacterinanyterminallocation(6,17," ");
printacharacterinanyterminallocation(6,18," ");
printacharacterinanyterminallocation(6,19," ");
printacharacterinanyterminallocation(6,20," ");
printacharacterinanyterminallocation(6,21," ");
printacharacterinanyterminallocation(6,22," ");
printacharacterinanyterminallocation(6,23," ");
printacharacterinanyterminallocation(6,24," ");
setBackgroundColor(3);
printacharacterinanyterminallocation(7,2,"D");
printacharacterinanyterminallocation(7,3,"e");
printacharacterinanyterminallocation(7,4,"l");
printacharacterinanyterminallocation(7,5,"e");
printacharacterinanyterminallocation(7,6,"t");
printacharacterinanyterminallocation(7,7,"e");
printacharacterinanyterminallocation(7,8," ");
printacharacterinanyterminallocation(7,9," ");
printacharacterinanyterminallocation(7,10," ");
printacharacterinanyterminallocation(7,11," ");
printacharacterinanyterminallocation(7,12," ");
printacharacterinanyterminallocation(7,13," ");
printacharacterinanyterminallocation(7,14," ");
printacharacterinanyterminallocation(7,15," ");
printacharacterinanyterminallocation(7,16," ");
printacharacterinanyterminallocation(7,17," ");
printacharacterinanyterminallocation(7,18," ");
printacharacterinanyterminallocation(7,19," ");
printacharacterinanyterminallocation(7,20," ");
printacharacterinanyterminallocation(7,21," ");
printacharacterinanyterminallocation(7,22," ");
printacharacterinanyterminallocation(7,23," ");
printacharacterinanyterminallocation(7,24," ");
setBackgroundColor(2);
printacharacterinanyterminallocation(8,2,"N");
printacharacterinanyterminallocation(8,3,"e");
printacharacterinanyterminallocation(8,4,"w");
printacharacterinanyterminallocation(8,5," ");
printacharacterinanyterminallocation(8,6,"f");
printacharacterinanyterminallocation(8,7,"o");
printacharacterinanyterminallocation(8,8,"l");
printacharacterinanyterminallocation(8,9,"d");
printacharacterinanyterminallocation(8,10,"e");
printacharacterinanyterminallocation(8,11,"r");
printacharacterinanyterminallocation(8,12," ");
printacharacterinanyterminallocation(8,13," ");
printacharacterinanyterminallocation(8,14," ");
printacharacterinanyterminallocation(8,15," ");
printacharacterinanyterminallocation(8,16," ");
printacharacterinanyterminallocation(8,17," ");
printacharacterinanyterminallocation(8,18," ");
printacharacterinanyterminallocation(8,19," ");
printacharacterinanyterminallocation(8,20," ");
printacharacterinanyterminallocation(8,21," ");
printacharacterinanyterminallocation(8,22," ");
printacharacterinanyterminallocation(8,23," ");
printacharacterinanyterminallocation(8,24," ");
printacharacterinanyterminallocation(9,2,"E");
printacharacterinanyterminallocation(9,3,"x");
printacharacterinanyterminallocation(9,4,"i");
printacharacterinanyterminallocation(9,5,"t");
printacharacterinanyterminallocation(9,6," ");
printacharacterinanyterminallocation(9,7," ");
printacharacterinanyterminallocation(9,8," ");
printacharacterinanyterminallocation(9,9," ");
printacharacterinanyterminallocation(9,10," ");
printacharacterinanyterminallocation(9,11," ");
printacharacterinanyterminallocation(9,12," ");
printacharacterinanyterminallocation(9,13," ");
printacharacterinanyterminallocation(9,14," ");
printacharacterinanyterminallocation(9,15," ");
printacharacterinanyterminallocation(9,16," ");
printacharacterinanyterminallocation(9,17," ");
printacharacterinanyterminallocation(9,18," ");
printacharacterinanyterminallocation(9,19," ");
printacharacterinanyterminallocation(9,20," ");
printacharacterinanyterminallocation(9,21," ");
printacharacterinanyterminallocation(9,22," ");
printacharacterinanyterminallocation(9,23," ");
printacharacterinanyterminallocation(9,24," ");
putchar('\n');
}
else if (xcoordinateformenubar == 6 && menubarmode == true){
printacharacterinanyterminallocation(3,2,"C");
printacharacterinanyterminallocation(3,3,"u");
printacharacterinanyterminallocation(3,4,"t");
printacharacterinanyterminallocation(3,5," ");
printacharacterinanyterminallocation(3,6," ");
printacharacterinanyterminallocation(3,7," ");
printacharacterinanyterminallocation(3,8," ");
printacharacterinanyterminallocation(3,9," ");
printacharacterinanyterminallocation(3,10," ");
printacharacterinanyterminallocation(3,11," ");
printacharacterinanyterminallocation(3,12," ");
printacharacterinanyterminallocation(3,13," ");
printacharacterinanyterminallocation(3,14," ");
printacharacterinanyterminallocation(3,15," ");
printacharacterinanyterminallocation(3,16," ");
printacharacterinanyterminallocation(3,17," ");
printacharacterinanyterminallocation(3,18," ");
printacharacterinanyterminallocation(3,19," ");
printacharacterinanyterminallocation(3,20," ");
printacharacterinanyterminallocation(3,21," ");
printacharacterinanyterminallocation(3,22," ");
printacharacterinanyterminallocation(3,23," ");
printacharacterinanyterminallocation(3,24," ");
printacharacterinanyterminallocation(4,2,"C");
printacharacterinanyterminallocation(4,3,"o");
printacharacterinanyterminallocation(4,4,"p");
printacharacterinanyterminallocation(4,5,"y");
printacharacterinanyterminallocation(4,6," ");
printacharacterinanyterminallocation(4,7," ");
printacharacterinanyterminallocation(4,8," ");
printacharacterinanyterminallocation(4,9," ");
printacharacterinanyterminallocation(4,10," ");
printacharacterinanyterminallocation(4,11," ");
printacharacterinanyterminallocation(4,12," ");
printacharacterinanyterminallocation(4,13," ");
printacharacterinanyterminallocation(4,14," ");
printacharacterinanyterminallocation(4,15," ");
printacharacterinanyterminallocation(4,16," ");
printacharacterinanyterminallocation(4,17," ");
printacharacterinanyterminallocation(4,18," ");
printacharacterinanyterminallocation(4,19," ");
printacharacterinanyterminallocation(4,20," ");
printacharacterinanyterminallocation(4,21," ");
printacharacterinanyterminallocation(4,22," ");
printacharacterinanyterminallocation(4,23," ");
printacharacterinanyterminallocation(4,24," ");
printacharacterinanyterminallocation(5,2,"P");
printacharacterinanyterminallocation(5,3,"a");
printacharacterinanyterminallocation(5,4,"s");
printacharacterinanyterminallocation(5,5,"t");
printacharacterinanyterminallocation(5,6,"e");
printacharacterinanyterminallocation(5,7," ");
printacharacterinanyterminallocation(5,8," ");
printacharacterinanyterminallocation(5,9," ");
printacharacterinanyterminallocation(5,10," ");
printacharacterinanyterminallocation(5,11," ");
printacharacterinanyterminallocation(5,12," ");
printacharacterinanyterminallocation(5,13," ");
printacharacterinanyterminallocation(5,14," ");
printacharacterinanyterminallocation(5,15," ");
printacharacterinanyterminallocation(5,16," ");
printacharacterinanyterminallocation(5,17," ");
printacharacterinanyterminallocation(5,18," ");
printacharacterinanyterminallocation(5,19," ");
printacharacterinanyterminallocation(5,20," ");
printacharacterinanyterminallocation(5,21," ");
printacharacterinanyterminallocation(5,22," ");
printacharacterinanyterminallocation(5,23," ");
printacharacterinanyterminallocation(5,24," ");
printacharacterinanyterminallocation(6,2,"R");
printacharacterinanyterminallocation(6,3,"e");
printacharacterinanyterminallocation(6,4,"n");
printacharacterinanyterminallocation(6,5,"a");
printacharacterinanyterminallocation(6,6,"m");
printacharacterinanyterminallocation(6,7,"e");
printacharacterinanyterminallocation(6,8," ");
printacharacterinanyterminallocation(6,9," ");
printacharacterinanyterminallocation(6,10," ");
printacharacterinanyterminallocation(6,11," ");
printacharacterinanyterminallocation(6,12," ");
printacharacterinanyterminallocation(6,13," ");
printacharacterinanyterminallocation(6,14," ");
printacharacterinanyterminallocation(6,15," ");
printacharacterinanyterminallocation(6,16," ");
printacharacterinanyterminallocation(6,17," ");
printacharacterinanyterminallocation(6,18," ");
printacharacterinanyterminallocation(6,19," ");
printacharacterinanyterminallocation(6,20," ");
printacharacterinanyterminallocation(6,21," ");
printacharacterinanyterminallocation(6,22," ");
printacharacterinanyterminallocation(6,23," ");
printacharacterinanyterminallocation(6,24," ");
printacharacterinanyterminallocation(7,2,"D");
printacharacterinanyterminallocation(7,3,"e");
printacharacterinanyterminallocation(7,4,"l");
printacharacterinanyterminallocation(7,5,"e");
printacharacterinanyterminallocation(7,6,"t");
printacharacterinanyterminallocation(7,7,"e");
printacharacterinanyterminallocation(7,8," ");
printacharacterinanyterminallocation(7,9," ");
printacharacterinanyterminallocation(7,10," ");
printacharacterinanyterminallocation(7,11," ");
printacharacterinanyterminallocation(7,12," ");
printacharacterinanyterminallocation(7,13," ");
printacharacterinanyterminallocation(7,14," ");
printacharacterinanyterminallocation(7,15," ");
printacharacterinanyterminallocation(7,16," ");
printacharacterinanyterminallocation(7,17," ");
printacharacterinanyterminallocation(7,18," ");
printacharacterinanyterminallocation(7,19," ");
printacharacterinanyterminallocation(7,20," ");
printacharacterinanyterminallocation(7,21," ");
printacharacterinanyterminallocation(7,22," ");
printacharacterinanyterminallocation(7,23," ");
printacharacterinanyterminallocation(7,24," ");
setBackgroundColor(3);
printacharacterinanyterminallocation(8,2,"N");
printacharacterinanyterminallocation(8,3,"e");
printacharacterinanyterminallocation(8,4,"w");
printacharacterinanyterminallocation(8,5," ");
printacharacterinanyterminallocation(8,6,"f");
printacharacterinanyterminallocation(8,7,"o");
printacharacterinanyterminallocation(8,8,"l");
printacharacterinanyterminallocation(8,9,"d");
printacharacterinanyterminallocation(8,10,"e");
printacharacterinanyterminallocation(8,11,"r");
printacharacterinanyterminallocation(8,12," ");
printacharacterinanyterminallocation(8,13," ");
printacharacterinanyterminallocation(8,14," ");
printacharacterinanyterminallocation(8,15," ");
printacharacterinanyterminallocation(8,16," ");
printacharacterinanyterminallocation(8,17," ");
printacharacterinanyterminallocation(8,18," ");
printacharacterinanyterminallocation(8,19," ");
printacharacterinanyterminallocation(8,20," ");
printacharacterinanyterminallocation(8,21," ");
printacharacterinanyterminallocation(8,22," ");
printacharacterinanyterminallocation(8,23," ");
printacharacterinanyterminallocation(8,24," ");
setBackgroundColor(2);
printacharacterinanyterminallocation(9,2,"E");
printacharacterinanyterminallocation(9,3,"x");
printacharacterinanyterminallocation(9,4,"i");
printacharacterinanyterminallocation(9,5,"t");
printacharacterinanyterminallocation(9,6," ");
printacharacterinanyterminallocation(9,7," ");
printacharacterinanyterminallocation(9,8," ");
printacharacterinanyterminallocation(9,9," ");
printacharacterinanyterminallocation(9,10," ");
printacharacterinanyterminallocation(9,11," ");
printacharacterinanyterminallocation(9,12," ");
printacharacterinanyterminallocation(9,13," ");
printacharacterinanyterminallocation(9,14," ");
printacharacterinanyterminallocation(9,15," ");
printacharacterinanyterminallocation(9,16," ");
printacharacterinanyterminallocation(9,17," ");
printacharacterinanyterminallocation(9,18," ");
printacharacterinanyterminallocation(9,19," ");
printacharacterinanyterminallocation(9,20," ");
printacharacterinanyterminallocation(9,21," ");
printacharacterinanyterminallocation(9,22," ");
printacharacterinanyterminallocation(9,23," ");
printacharacterinanyterminallocation(9,24," ");
putchar('\n');
}
else if (xcoordinateformenubar == 7 && menubarmode == true){
printacharacterinanyterminallocation(3,2,"C");
printacharacterinanyterminallocation(3,3,"u");
printacharacterinanyterminallocation(3,4,"t");
printacharacterinanyterminallocation(3,5," ");
printacharacterinanyterminallocation(3,6," ");
printacharacterinanyterminallocation(3,7," ");
printacharacterinanyterminallocation(3,8," ");
printacharacterinanyterminallocation(3,9," ");
printacharacterinanyterminallocation(3,10," ");
printacharacterinanyterminallocation(3,11," ");
printacharacterinanyterminallocation(3,12," ");
printacharacterinanyterminallocation(3,13," ");
printacharacterinanyterminallocation(3,14," ");
printacharacterinanyterminallocation(3,15," ");
printacharacterinanyterminallocation(3,16," ");
printacharacterinanyterminallocation(3,17," ");
printacharacterinanyterminallocation(3,18," ");
printacharacterinanyterminallocation(3,19," ");
printacharacterinanyterminallocation(3,20," ");
printacharacterinanyterminallocation(3,21," ");
printacharacterinanyterminallocation(3,22," ");
printacharacterinanyterminallocation(3,23," ");
printacharacterinanyterminallocation(3,24," ");
printacharacterinanyterminallocation(4,2,"C");
printacharacterinanyterminallocation(4,3,"o");
printacharacterinanyterminallocation(4,4,"p");
printacharacterinanyterminallocation(4,5,"y");
printacharacterinanyterminallocation(4,6," ");
printacharacterinanyterminallocation(4,7," ");
printacharacterinanyterminallocation(4,8," ");
printacharacterinanyterminallocation(4,9," ");
printacharacterinanyterminallocation(4,10," ");
printacharacterinanyterminallocation(4,11," ");
printacharacterinanyterminallocation(4,12," ");
printacharacterinanyterminallocation(4,13," ");
printacharacterinanyterminallocation(4,14," ");
printacharacterinanyterminallocation(4,15," ");
printacharacterinanyterminallocation(4,16," ");
printacharacterinanyterminallocation(4,17," ");
printacharacterinanyterminallocation(4,18," ");
printacharacterinanyterminallocation(4,19," ");
printacharacterinanyterminallocation(4,20," ");
printacharacterinanyterminallocation(4,21," ");
printacharacterinanyterminallocation(4,22," ");
printacharacterinanyterminallocation(4,23," ");
printacharacterinanyterminallocation(4,24," ");
printacharacterinanyterminallocation(5,2,"P");
printacharacterinanyterminallocation(5,3,"a");
printacharacterinanyterminallocation(5,4,"s");
printacharacterinanyterminallocation(5,5,"t");
printacharacterinanyterminallocation(5,6,"e");
printacharacterinanyterminallocation(5,7," ");
printacharacterinanyterminallocation(5,8," ");
printacharacterinanyterminallocation(5,9," ");
printacharacterinanyterminallocation(5,10," ");
printacharacterinanyterminallocation(5,11," ");
printacharacterinanyterminallocation(5,12," ");
printacharacterinanyterminallocation(5,13," ");
printacharacterinanyterminallocation(5,14," ");
printacharacterinanyterminallocation(5,15," ");
printacharacterinanyterminallocation(5,16," ");
printacharacterinanyterminallocation(5,17," ");
printacharacterinanyterminallocation(5,18," ");
printacharacterinanyterminallocation(5,19," ");
printacharacterinanyterminallocation(5,20," ");
printacharacterinanyterminallocation(5,21," ");
printacharacterinanyterminallocation(5,22," ");
printacharacterinanyterminallocation(5,23," ");
printacharacterinanyterminallocation(5,24," ");
printacharacterinanyterminallocation(6,2,"R");
printacharacterinanyterminallocation(6,3,"e");
printacharacterinanyterminallocation(6,4,"n");
printacharacterinanyterminallocation(6,5,"a");
printacharacterinanyterminallocation(6,6,"m");
printacharacterinanyterminallocation(6,7,"e");
printacharacterinanyterminallocation(6,8," ");
printacharacterinanyterminallocation(6,9," ");
printacharacterinanyterminallocation(6,10," ");
printacharacterinanyterminallocation(6,11," ");
printacharacterinanyterminallocation(6,12," ");
printacharacterinanyterminallocation(6,13," ");
printacharacterinanyterminallocation(6,14," ");
printacharacterinanyterminallocation(6,15," ");
printacharacterinanyterminallocation(6,16," ");
printacharacterinanyterminallocation(6,17," ");
printacharacterinanyterminallocation(6,18," ");
printacharacterinanyterminallocation(6,19," ");
printacharacterinanyterminallocation(6,20," ");
printacharacterinanyterminallocation(6,21," ");
printacharacterinanyterminallocation(6,22," ");
printacharacterinanyterminallocation(6,23," ");
printacharacterinanyterminallocation(6,24," ");
printacharacterinanyterminallocation(7,2,"D");
printacharacterinanyterminallocation(7,3,"e");
printacharacterinanyterminallocation(7,4,"l");
printacharacterinanyterminallocation(7,5,"e");
printacharacterinanyterminallocation(7,6,"t");
printacharacterinanyterminallocation(7,7,"e");
printacharacterinanyterminallocation(7,8," ");
printacharacterinanyterminallocation(7,9," ");
printacharacterinanyterminallocation(7,10," ");
printacharacterinanyterminallocation(7,11," ");
printacharacterinanyterminallocation(7,12," ");
printacharacterinanyterminallocation(7,13," ");
printacharacterinanyterminallocation(7,14," ");
printacharacterinanyterminallocation(7,15," ");
printacharacterinanyterminallocation(7,16," ");
printacharacterinanyterminallocation(7,17," ");
printacharacterinanyterminallocation(7,18," ");
printacharacterinanyterminallocation(7,19," ");
printacharacterinanyterminallocation(7,20," ");
printacharacterinanyterminallocation(7,21," ");
printacharacterinanyterminallocation(7,22," ");
printacharacterinanyterminallocation(7,23," ");
printacharacterinanyterminallocation(7,24," ");
printacharacterinanyterminallocation(8,2,"N");
printacharacterinanyterminallocation(8,3,"e");
printacharacterinanyterminallocation(8,4,"w");
printacharacterinanyterminallocation(8,5," ");
printacharacterinanyterminallocation(8,6,"f");
printacharacterinanyterminallocation(8,7,"o");
printacharacterinanyterminallocation(8,8,"l");
printacharacterinanyterminallocation(8,9,"d");
printacharacterinanyterminallocation(8,10,"e");
printacharacterinanyterminallocation(8,11,"r");
printacharacterinanyterminallocation(8,12," ");
printacharacterinanyterminallocation(8,13," ");
printacharacterinanyterminallocation(8,14," ");
printacharacterinanyterminallocation(8,15," ");
printacharacterinanyterminallocation(8,16," ");
printacharacterinanyterminallocation(8,17," ");
printacharacterinanyterminallocation(8,18," ");
printacharacterinanyterminallocation(8,19," ");
printacharacterinanyterminallocation(8,20," ");
printacharacterinanyterminallocation(8,21," ");
printacharacterinanyterminallocation(8,22," ");
printacharacterinanyterminallocation(8,23," ");
printacharacterinanyterminallocation(8,24," ");
setBackgroundColor(3);
printacharacterinanyterminallocation(9,2,"E");
printacharacterinanyterminallocation(9,3,"x");
printacharacterinanyterminallocation(9,4,"i");
printacharacterinanyterminallocation(9,5,"t");
printacharacterinanyterminallocation(9,6," ");
printacharacterinanyterminallocation(9,7," ");
printacharacterinanyterminallocation(9,8," ");
printacharacterinanyterminallocation(9,9," ");
printacharacterinanyterminallocation(9,10," ");
printacharacterinanyterminallocation(9,11," ");
printacharacterinanyterminallocation(9,12," ");
printacharacterinanyterminallocation(9,13," ");
printacharacterinanyterminallocation(9,14," ");
printacharacterinanyterminallocation(9,15," ");
printacharacterinanyterminallocation(9,16," ");
printacharacterinanyterminallocation(9,17," ");
printacharacterinanyterminallocation(9,18," ");
printacharacterinanyterminallocation(9,19," ");
printacharacterinanyterminallocation(9,20," ");
printacharacterinanyterminallocation(9,21," ");
printacharacterinanyterminallocation(9,22," ");
printacharacterinanyterminallocation(9,23," ");
printacharacterinanyterminallocation(9,24," ");
setBackgroundColor(2);
putchar('\n');
}
}
void closemenubar() {
menubarmode = false;
setBackgroundColor(4);
printacharacterinanyterminallocation(2,1," ");
printacharacterinanyterminallocation(3,1," ");
printacharacterinanyterminallocation(4,1," ");
printacharacterinanyterminallocation(5,1," ");
printacharacterinanyterminallocation(6,1," ");
printacharacterinanyterminallocation(7,1," ");
printacharacterinanyterminallocation(8,1," ");
printacharacterinanyterminallocation(9,1," ");
printacharacterinanyterminallocation(10,1," ");
printacharacterinanyterminallocation(10,2," ");
printacharacterinanyterminallocation(10,3," ");
printacharacterinanyterminallocation(10,4," ");
printacharacterinanyterminallocation(10,5," ");
printacharacterinanyterminallocation(10,6," ");
printacharacterinanyterminallocation(10,7," ");
printacharacterinanyterminallocation(10,8," ");
printacharacterinanyterminallocation(10,9," ");
printacharacterinanyterminallocation(10,10," ");
printacharacterinanyterminallocation(10,11," ");
printacharacterinanyterminallocation(10,12," ");
printacharacterinanyterminallocation(10,13," ");
printacharacterinanyterminallocation(10,14," ");
printacharacterinanyterminallocation(10,15," ");
printacharacterinanyterminallocation(10,16," ");
printacharacterinanyterminallocation(10,17," ");
printacharacterinanyterminallocation(10,18," ");
printacharacterinanyterminallocation(10,19," ");
printacharacterinanyterminallocation(10,20," ");
printacharacterinanyterminallocation(10,21," ");
printacharacterinanyterminallocation(10,22," ");
printacharacterinanyterminallocation(10,23," ");
printacharacterinanyterminallocation(10,24," ");
printacharacterinanyterminallocation(10,25," ");
printacharacterinanyterminallocation(3,25," ");
printacharacterinanyterminallocation(4,25," ");
printacharacterinanyterminallocation(5,25," ");
printacharacterinanyterminallocation(6,25," ");
printacharacterinanyterminallocation(7,25," ");
printacharacterinanyterminallocation(8,25," ");
printacharacterinanyterminallocation(9,25," ");
printacharacterinanyterminallocation(2,25," ");
printacharacterinanyterminallocation(2,24," ");
printacharacterinanyterminallocation(2,23," ");
printacharacterinanyterminallocation(2,22," ");
printacharacterinanyterminallocation(2,21," ");
printacharacterinanyterminallocation(2,20," ");
printacharacterinanyterminallocation(2,19," ");
printacharacterinanyterminallocation(2,18," ");
printacharacterinanyterminallocation(2,17," ");
printacharacterinanyterminallocation(2,16," ");
printacharacterinanyterminallocation(2,15," ");
printacharacterinanyterminallocation(2,14," ");
printacharacterinanyterminallocation(2,13," ");
printacharacterinanyterminallocation(2,12," ");
printacharacterinanyterminallocation(2,11," ");
printacharacterinanyterminallocation(2,10," ");
printacharacterinanyterminallocation(2,9," ");
printacharacterinanyterminallocation(2,8," ");
printacharacterinanyterminallocation(2,7," ");
printacharacterinanyterminallocation(2,6," ");
printacharacterinanyterminallocation(2,5," ");
printacharacterinanyterminallocation(2,4," ");
printacharacterinanyterminallocation(2,3," ");
printacharacterinanyterminallocation(2,2," ");
printacharacterinanyterminallocation(3,2," ");
printacharacterinanyterminallocation(3,3," ");
printacharacterinanyterminallocation(3,4," ");
printacharacterinanyterminallocation(3,5," ");
printacharacterinanyterminallocation(3,6," ");
printacharacterinanyterminallocation(3,7," ");
printacharacterinanyterminallocation(3,8," ");
printacharacterinanyterminallocation(3,9," ");
printacharacterinanyterminallocation(3,10," ");
printacharacterinanyterminallocation(3,11," ");
printacharacterinanyterminallocation(3,12," ");
printacharacterinanyterminallocation(3,13," ");
printacharacterinanyterminallocation(3,14," ");
printacharacterinanyterminallocation(3,15," ");
printacharacterinanyterminallocation(3,16," ");
printacharacterinanyterminallocation(3,17," ");
printacharacterinanyterminallocation(3,18," ");
printacharacterinanyterminallocation(3,19," ");
printacharacterinanyterminallocation(3,20," ");
printacharacterinanyterminallocation(3,21," ");
printacharacterinanyterminallocation(3,22," ");
printacharacterinanyterminallocation(3,23," ");
printacharacterinanyterminallocation(3,24," ");
printacharacterinanyterminallocation(4,2," ");
printacharacterinanyterminallocation(4,3," ");
printacharacterinanyterminallocation(4,4," ");
printacharacterinanyterminallocation(4,5," ");
printacharacterinanyterminallocation(4,6," ");
printacharacterinanyterminallocation(4,7," ");
printacharacterinanyterminallocation(4,8," ");
printacharacterinanyterminallocation(4,9," ");
printacharacterinanyterminallocation(4,10," ");
printacharacterinanyterminallocation(4,11," ");
printacharacterinanyterminallocation(4,12," ");
printacharacterinanyterminallocation(4,13," ");
printacharacterinanyterminallocation(4,14," ");
printacharacterinanyterminallocation(4,15," ");
printacharacterinanyterminallocation(4,16," ");
printacharacterinanyterminallocation(4,17," ");
printacharacterinanyterminallocation(4,18," ");
printacharacterinanyterminallocation(4,19," ");
printacharacterinanyterminallocation(4,20," ");
printacharacterinanyterminallocation(4,21," ");
printacharacterinanyterminallocation(4,22," ");
printacharacterinanyterminallocation(4,23," ");
printacharacterinanyterminallocation(4,24," ");
printacharacterinanyterminallocation(5,2," ");
printacharacterinanyterminallocation(5,3," ");
printacharacterinanyterminallocation(5,4," ");
printacharacterinanyterminallocation(5,5," ");
printacharacterinanyterminallocation(5,6," ");
printacharacterinanyterminallocation(5,7," ");
printacharacterinanyterminallocation(5,8," ");
printacharacterinanyterminallocation(5,9," ");
printacharacterinanyterminallocation(5,10," ");
printacharacterinanyterminallocation(5,11," ");
printacharacterinanyterminallocation(5,12," ");
printacharacterinanyterminallocation(5,13," ");
printacharacterinanyterminallocation(5,14," ");
printacharacterinanyterminallocation(5,15," ");
printacharacterinanyterminallocation(5,16," ");
printacharacterinanyterminallocation(5,17," ");
printacharacterinanyterminallocation(5,18," ");
printacharacterinanyterminallocation(5,19," ");
printacharacterinanyterminallocation(5,20," ");
printacharacterinanyterminallocation(5,21," ");
printacharacterinanyterminallocation(5,22," ");
printacharacterinanyterminallocation(5,23," ");
printacharacterinanyterminallocation(5,24," ");
printacharacterinanyterminallocation(6,2," ");
printacharacterinanyterminallocation(6,3," ");
printacharacterinanyterminallocation(6,4," ");
printacharacterinanyterminallocation(6,5," ");
printacharacterinanyterminallocation(6,6," ");
printacharacterinanyterminallocation(6,7," ");
printacharacterinanyterminallocation(6,8," ");
printacharacterinanyterminallocation(6,9," ");
printacharacterinanyterminallocation(6,10," ");
printacharacterinanyterminallocation(6,11," ");
printacharacterinanyterminallocation(6,12," ");
printacharacterinanyterminallocation(6,13," ");
printacharacterinanyterminallocation(6,14," ");
printacharacterinanyterminallocation(6,15," ");
printacharacterinanyterminallocation(6,16," ");
printacharacterinanyterminallocation(6,17," ");
printacharacterinanyterminallocation(6,18," ");
printacharacterinanyterminallocation(6,19," ");
printacharacterinanyterminallocation(6,20," ");
printacharacterinanyterminallocation(6,21," ");
printacharacterinanyterminallocation(6,22," ");
printacharacterinanyterminallocation(6,23," ");
printacharacterinanyterminallocation(6,24," ");
printacharacterinanyterminallocation(7,2," ");
printacharacterinanyterminallocation(7,3," ");
printacharacterinanyterminallocation(7,4," ");
printacharacterinanyterminallocation(7,5," ");
printacharacterinanyterminallocation(7,6," ");
printacharacterinanyterminallocation(7,7," ");
printacharacterinanyterminallocation(7,8," ");
printacharacterinanyterminallocation(7,9," ");
printacharacterinanyterminallocation(7,10," ");
printacharacterinanyterminallocation(7,11," ");
printacharacterinanyterminallocation(7,12," ");
printacharacterinanyterminallocation(7,13," ");
printacharacterinanyterminallocation(7,14," ");
printacharacterinanyterminallocation(7,15," ");
printacharacterinanyterminallocation(7,16," ");
printacharacterinanyterminallocation(7,17," ");
printacharacterinanyterminallocation(7,18," ");
printacharacterinanyterminallocation(7,19," ");
printacharacterinanyterminallocation(7,20," ");
printacharacterinanyterminallocation(7,21," ");
printacharacterinanyterminallocation(7,22," ");
printacharacterinanyterminallocation(7,23," ");
printacharacterinanyterminallocation(7,24," ");
printacharacterinanyterminallocation(8,2," ");
printacharacterinanyterminallocation(8,3," ");
printacharacterinanyterminallocation(8,4," ");
printacharacterinanyterminallocation(8,5," ");
printacharacterinanyterminallocation(8,6," ");
printacharacterinanyterminallocation(8,7," ");
printacharacterinanyterminallocation(8,8," ");
printacharacterinanyterminallocation(8,9," ");
printacharacterinanyterminallocation(8,10," ");
printacharacterinanyterminallocation(8,11," ");
printacharacterinanyterminallocation(8,12," ");
printacharacterinanyterminallocation(8,13," ");
printacharacterinanyterminallocation(8,14," ");
printacharacterinanyterminallocation(8,15," ");
printacharacterinanyterminallocation(8,16," ");
printacharacterinanyterminallocation(8,17," ");
printacharacterinanyterminallocation(8,18," ");
printacharacterinanyterminallocation(8,19," ");
printacharacterinanyterminallocation(8,20," ");
printacharacterinanyterminallocation(8,21," ");
printacharacterinanyterminallocation(8,22," ");
printacharacterinanyterminallocation(8,23," ");
printacharacterinanyterminallocation(8,24," ");
printacharacterinanyterminallocation(9,2," ");
printacharacterinanyterminallocation(9,3," ");
printacharacterinanyterminallocation(9,4," ");
printacharacterinanyterminallocation(9,5," ");
printacharacterinanyterminallocation(9,6," ");
printacharacterinanyterminallocation(9,7," ");
printacharacterinanyterminallocation(9,8," ");
printacharacterinanyterminallocation(9,9," ");
printacharacterinanyterminallocation(9,10," ");
printacharacterinanyterminallocation(9,11," ");
printacharacterinanyterminallocation(9,12," ");
printacharacterinanyterminallocation(9,13," ");
printacharacterinanyterminallocation(9,14," ");
printacharacterinanyterminallocation(9,15," ");
printacharacterinanyterminallocation(9,16," ");
printacharacterinanyterminallocation(9,17," ");
printacharacterinanyterminallocation(9,18," ");
printacharacterinanyterminallocation(9,19," ");
printacharacterinanyterminallocation(9,20," ");
printacharacterinanyterminallocation(9,21," ");
printacharacterinanyterminallocation(9,22," ");
printacharacterinanyterminallocation(9,23," ");
printacharacterinanyterminallocation(9,24," ");
putchar('\n');
drawingoffilesboxdone = false;
int backup = driveslistingscount;
driveslistingscount = backup;
drawdrivesbox();
driveslistingscount = backup;
drawingoffilesboxdone = true;
xcoordinateformenubar = 0;
setBackgroundColor(2);
printacharacterinanyterminallocation(1,1,"F");
printacharacterinanyterminallocation(1,2,"i");
printacharacterinanyterminallocation(1,3,"l");
printacharacterinanyterminallocation(1,4,"e");
setBackgroundColor(4);
putchar('\n');
}
