#ifndef SHOWDELETEFILEANDDIRECTORYDIALOGS_H_INCLUDED
#define SHOWDELETEFILEANDDIRECTORYDIALOGS_H_INCLUDED

int showdeletefiledialog();
int showdeletedirectorydialog();

#endif // SHOWDELETEFILEANDDIRECTORYDIALOGS_H_INCLUDED
